server:
  port: ${port}  #服务端口

spring:
  application:
    name: SpringGateWay  #服务名

eureka:
  client:
    registerWithEureka: true  #是否注册自己到eureka服务中，默认不注册
    fetchRegistry: true     #是否从eureka服务中获取注册信息
    serviceUrl:   #eureka客户端与服务器交互的地址
      defaultZone: http://127.0.0.1:6871/eureka/,http://127.0.0.1:6872/eureka/ #自己注册到eureka那个服务,可注册多个，用，分隔
    eurekaServerConnectTimeoutSeconds: 60
    eurekaServerReadTimeoutSeconds: 60
  instance:
    prefer-ip-address: true  #将自己的ip注册到eeureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    lease-expiration-duration-in-seconds: 30   #续约更新时间间隔
    lease-renewal--interval-in-seconds: 10     #续约到期时间间隔，默认90
    leaseRenewalIntervalInSeconds: 10     #心跳时间

zuul:
  routes:
    usermanager-service: #用户测试服务，名称随意
      path: /usermanager/** #请求过滤规则,这里可以是任意名称，url包含就行，包含跳转到serviceId配置的服务中请求
      serviceId: usermanager   #服务名
      #url:   #真正的微服务地址
    SpringRibbon-service:  #请求过滤规则,这里可以是任意名称，url包含就行，包含跳转到serviceId配置的服务中请求
          path: /userInfomanager/** #请求过滤规则
          serviceId: SpringRibbon    #服务名
          #url:   #真正的微服务地址
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000




